// Redux slice for managing Person state
import { createSlice, createAsyncThunk, PayloadAction } from '@reduxjs/toolkit';
import { PersonLookUpResponse, PersonenQuery, PersonResponse } from '../../taskpane/components/interfaces/IPerson';
import { getWebRTCConnectionManager } from '../../taskpane/services/WebRTCConnectionManager';

// State interface
interface PersonState {
  persons: PersonLookUpResponse[];
  loading: boolean;
  error: string | null;
  searchTerm: string; // Current search term in the search box
  favorites: PersonResponse[]; // For favorite persons from GetAllAsync endpoint
  favoritesLoading: boolean;
}

// Initial state
const initialState: PersonState = {
  persons: [],
  loading: false,
  error: null,
  searchTerm: '',
  favorites: [],
  favoritesLoading: false
};

// Main async thunk for Person lookup with text search
export const personLookUpAsync = createAsyncThunk(
  'person/personLookUp',
  async (searchText: string) => {
    const connectionManager = getWebRTCConnectionManager();
    const webRTCApiService = connectionManager.getWebRTCApiService();
    
    const response = await webRTCApiService.personLookUp(searchText);
    if (response.response.statusCode === 200) {
      return JSON.parse(response.response.body || '[]') as PersonLookUpResponse[];
    } else {
      throw new Error('Failed to lookup persons');
    }
  }
);

// New async thunk for getting favorite persons
export const getFavoritePersonsAsync = createAsyncThunk(
  'person/getFavoritePersons',
  async (query: PersonenQuery) => {
    const connectionManager = getWebRTCConnectionManager();
    const webRTCApiService = connectionManager.getWebRTCApiService();
    
    const response = await webRTCApiService.getFavoritePersons(query);
    if (response.response.statusCode === 200) {
      return JSON.parse(response.response.body || '[]') as PersonResponse[];
    } else {
      throw new Error('Failed to get favorite persons');
    }
  }
);

// Add person to favorites - calls API and refreshes favorites list
export const addPersonToFavoritesAsync = createAsyncThunk(
  'person/addToFavorites',
  async (personId: number, { dispatch }) => {
    const connectionManager = getWebRTCConnectionManager();
    const webRTCApiService = connectionManager.getWebRTCApiService();
    const response = await webRTCApiService.addPersonToFavorites(personId);
    
    if (response.response.statusCode === 200) {
      // Refresh favorites list after successful addition
      dispatch(getFavoritePersonsAsync({ Count: 100, NurFavoriten: true }));
      return personId;
    } else {
      throw new Error('Failed to add person to favorites');
    }
  }
);

// Remove person from favorites - calls API and refreshes favorites list
export const removePersonFromFavoritesAsync = createAsyncThunk(
  'person/removeFromFavorites',
  async (personId: number, { dispatch }) => {
    const connectionManager = getWebRTCConnectionManager();
    const webRTCApiService = connectionManager.getWebRTCApiService();
    const response = await webRTCApiService.removePersonFromFavorites(personId);
    
    if (response.response.statusCode === 200) {
      // Refresh favorites list after successful removal
      dispatch(getFavoritePersonsAsync({ Count: 100, NurFavoriten: true }));
      return personId;
    } else {
      throw new Error('Failed to remove person from favorites');
    }
  }
);

// Create slice
const personSlice = createSlice({
  name: 'person',
  initialState,
  reducers: {
    // Clear the persons list
    clearPersons: (state) => {
      state.persons = [];
      state.favorites = [];
      state.error = null;
    },
    // Set current search term
    setSearchTerm: (state, action: PayloadAction<string>) => {
      state.searchTerm = action.payload;
    },
    // Clear any error state
    clearError: (state) => {
      state.error = null;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      // Person lookup handlers
      .addCase(personLookUpAsync.pending, (state, action) => {
        state.loading = true;
        state.error = null;
        // Set searchTerm for lookup search
        state.searchTerm = action.meta.arg || '';
      })
      .addCase(personLookUpAsync.fulfilled, (state, action) => {
        state.loading = false;
        state.persons = action.payload;
      })
      .addCase(personLookUpAsync.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message || 'Failed to lookup persons via WebRTC';
      })
      // Get favorite persons handlers
      .addCase(getFavoritePersonsAsync.pending, (state) => {
        state.favoritesLoading = true;
        state.error = null;
      })
      .addCase(getFavoritePersonsAsync.fulfilled, (state, action) => {
        state.favoritesLoading = false;
        state.favorites = action.payload;
      })
      .addCase(getFavoritePersonsAsync.rejected, (state, action) => {
        state.favoritesLoading = false;
        state.error = action.error.message || 'Failed to get favorite persons via WebRTC';
      })
      // Add to favorites handlers
      .addCase(addPersonToFavoritesAsync.fulfilled, (_state, action) => {
        // Favorites list is refreshed automatically by the async thunk
        console.log('✅ Person added to favorites on server:', action.payload);
      })
      .addCase(addPersonToFavoritesAsync.rejected, (state, action) => {
        state.error = action.error.message || 'Failed to add person to favorites';
      })
      // Remove from favorites handlers
      .addCase(removePersonFromFavoritesAsync.fulfilled, (_state, action) => {
        // Favorites list is refreshed automatically by the async thunk
        console.log('✅ Person removed from favorites on server:', action.payload);
      })
      .addCase(removePersonFromFavoritesAsync.rejected, (state, action) => {
        state.error = action.error.message || 'Failed to remove person from favorites';
      });
  }
});

// Export actions
export const { 
  clearPersons, 
  setSearchTerm, 
  clearError
} = personSlice.actions;

// Export reducer
export default personSlice.reducer;
